services: docker
sudo: required
dist: xenial

language: go
go:
  - 1.13.x

env:
  global:
    - PATH=/opt/python/3.6.7/bin:$PATH
    - GO111MODULE=on
    - KUBE_VERSION="v1.16.2"
    - OP_VER="v0.11.0"
    - CSI_OP_VER="${TRAVIS_BRANCH}.${TRAVIS_OS_NAME}"
    - QUAY_USERNAME="mew2057"
    - DOCKER_REPO="quay.io/${QUAY_USERNAME}/ibm-spectrum-scale-csi-operator-test:${CSI_OP_VER}"

    - OPERATOR_SDK="https://github.com/operator-framework/operator-sdk/releases/download/${OP_VER}/operator-sdk-${OP_VER}-x86_64-linux-gnu"
    - CSI_OP_BUILD_DIR="${TRAVIS_BUILD_DIR}/stable/ibm-spectrum-scale-csi-operator-bundle/operators/ibm-spectrum-scale-csi-operator"


    - OPERATOR_NAME=ibm-spectrum-scale-csi-operator
    - OLM_MANIFEST="${CSI_OP_BUILD_DIR}/deploy/olm-catalog/${OPERATOR_NAME}/"

    - CHANGE_MINIKUBE_NONE_USER=true
    - MINIKUBE_WANTUPDATENOTIFICATION=false
    - MINIKUBE_WANTREPORTERRORPROMPT=false
    - MINIKUBE_HOME=$HOME
    - KUBECONFIG=$HOME/.kube/config

addons:
  apt:
    packages:
      - "python3"
      - "python3-dev"
      - "python3-pip" 
stages:
  - lint
  - build
  - test
jobs:
  fast_finish: true
  include:
    
    # Install operator-courier and run the lint on the manifest.
    - stage: lint
      script:
        - pip install operator-courier 
        - operator-courier verify --ui_validate_io ${OLM_MANIFEST}

    - stage: build
      script:
        - sudo pip install docker
        - ${TRAVIS_BUILD_DIR}/scripts/ci/install_operator-sdk.sh
        - cd ${CSI_OP_BUILD_DIR}
        - operator-sdk version
        - go version
        - operator-sdk build csi-scale-operator
        - docker tag csi-scale-operator ${DOCKER_REPO}
        - echo "$QUAY_BOT_PASSWORD" | docker login -u "$QUAY_BOT_USERNAME" --password-stdin quay.io 
        - docker push ${DOCKER_REPO} 

    # Install minikube, build the image and run the scorecard.
    - stage: test
      before_install:
        - sudo pip install docker
        - pip install openshift
        - ${TRAVIS_BUILD_DIR}/scripts/ci/install_minikube.sh
        - ${TRAVIS_BUILD_DIR}/scripts/ci/install_operator-sdk.sh
        - kubectl version
        - cd ${CSI_OP_BUILD_DIR}
      script: 
        # Print environment 
        # Build the image, clear and restore the finalizers.
        #- python hacks/clear_finalizers.py
        - python hacks/change_deploy_image.py ${DOCKER_REPO}
        - operator-sdk scorecard --config .osdk-scorecard.yaml
        #- python  hacks/clear_finalizers.py --restore
        
    - before_install:
        - sudo pip install docker
        - pip install pyyaml molecule openshift docker jmespath
        - ${TRAVIS_BUILD_DIR}/scripts/ci/install_minikube.sh
        - kubectl version
        - cd ${CSI_OP_BUILD_DIR}
      script: 
        #  This needs to be built before we can test with molecule for reasons.
        - python hacks/change_deploy_image.py ${DOCKER_REPO}
        - molecule test -s test-local

          #- ${TRAVIS_BUILD_DIR}/scripts/ci/fold_ouput.sh cluster.info.2 "cluster information"  kubectl cluster-info dump
notifications:
  email:
    - jdunham@us.ibm.com
