services: docker
language: go
sudo: required
install:
  - sudo pip install docker 
    #molecule openshift
go:
  - 1.13.x
stages:
  - Prep Scripts
  - Build Image
jobs:
  fast_finish: true
  include:
    - stage: Build Image
      script: 
        - sudo curl -L ${OPERATOR_SDK} -o /usr/local/bin/operator-sdk
        - sudo chmod +x /usr/local/bin/operator-sdk
        - cd ${CSI_OP_BUILD_DIR}
        - operator-sdk build csi-scale-operator
env:
  global:
    - GO111MODULE=on
    - CSI_OP_BUILD_DIR="${TRAVIS_BUILD_DIR}/stable/ibm-spectrum-scale-csi-operator-bundle/operators/ibm-spectrum-scale-csi-operator"
    - OPERATOR_SDK="https://github.com/operator-framework/operator-sdk/releases/download/v0.10.0/operator-sdk-v0.10.0-x86_64-linux-gnu"
