services: docker
sudo: required
dist: xenial

language: go
go:
  - 1.13.x

env:
  global:
    - GO111MODULE=on
    - KUBE_VERSION="v1.16.2"
    - OP_VER="v0.10.0"
    - CSI_OP_VER="0.0.1"
    - QUAY_USERNAME="mew2057"

    - OPERATOR_SDK="https://github.com/operator-framework/operator-sdk/releases/download/${OP_VER}/operator-sdk-${OP_VER}-x86_64-linux-gnu"

    - CSI_OP_BUILD_DIR="${TRAVIS_BUILD_DIR}/stable/ibm-spectrum-scale-csi-operator-bundle/operators/ibm-spectrum-scale-csi-operator"
    - DOCKER_REPO="quay.io/${QUAY_USERNAME}/ibm-spectrum-scale-csi-operator:v0.0.1"

    - OPERATOR_NAME=ibm-spectrum-scale-csi-operator
    - OLM_MANIFEST="${CSI_OP_BUILD_DIR}/deploy/olm-catalog/${OPERATOR_NAME}/"

    # TODO replace his with something better.
    - SC_VARS="--config .osdk-scorecard.yaml --cr-manifest  deploy/crds/ibm_v1alpha1_csiscaleoperator_cr.yaml  --csv-path deploy/olm-catalog/ibm-spectrum-scale-csi-operator/${CSI_OP_VER}/ibm-spectrum-scale-csi-operator.v${CSI_OP_VER}.clusterserviceversion.yaml"

    - CHANGE_MINIKUBE_NONE_USER=true
    - MINIKUBE_WANTUPDATENOTIFICATION=false
    - MINIKUBE_WANTREPORTERRORPROMPT=false
    - MINIKUBE_HOME=$HOME
    - KUBECONFIG=$HOME/.kube/config

stages:
  - courier-lint
  - scorecard
jobs:
  fast_finish: true
  include:
    
    # Install operator-courier and run the lint on the manifest.
    - stage: courier-lint
      script:
        - pyenv global 3.7
        - pip install operator-courier 
        - operator-courier verify --ui_validate_io ${OLM_MANIFEST}

    # Install minikube, build the image and run the scorecard.
    - stage: scorecard
      script: 
        - sudo pip install docker 
        - ${TRAVIS_BUILD_DIR}/scripts/ci/install_minikube.sh
        - ${TRAVIS_BUILD_DIR}/scripts/ci/install_operator-sdk.sh
        - cd ${CSI_OP_BUILD_DIR}
        - operator-sdk build csi-scale-operator
        - docker tag csi-scale-operator ${DOCKER_REPO}
        - operator-sdk scorecard ${SC_VARS}
        
        #- echo "$QUAY_BOT_PASSWORD" | docker login -u "$QUAY_BOT_USERNAME" --password-stdin quay.io 
        #- docker push ${DOCKER_REPO} 
notifications:
  email:
    - jdunham@us.ibm.com
