apiVersion: scale.ibm.com/v1alpha1
kind: 'CSIScaleOperator'
metadata: 
    # IMPORTANT THE OPERATOR LOOKS FOR THIS!
    name: 'csi-scale-operator'
status: {}
spec: 
  # 
  csi_scale_hostpath: "/ibm/fs1"

  csi_clusters: 
    - id: "2120508922778391120"
      secrets: "secret1"
      secureSslMode: false
      primary:
        primaryFS: "fs1"
        primaryFset: "csiFset2"
      restAPI: 
        - guiHost: "doomfang-vm5.tuc.stglabs.ibm.com"

