--- 
- name: Ensure secret {{ item.secrets }} defined in {{ lookup( 'vars','namespace' ) }}
  k8s_facts:
    kind: secrets
    namespace: "{{ lookup( 'vars','namespace' ) }}"
    name : "{{ item.secrets }}"
  register: results
  failed_when: results is not defined

#- name: Cache resources
#  set_fact:
#    resources: "{{results.resources}}"

- name: "Label unlabled secrets"
  include_tasks: password_label.yml
  when: item.metadata.label is not defined or
    item.metadata.label["app.kubernetes.io/name"] is not defined or
    item.metadata.label["app.kubernetes.io/name"] != "csi-scale-operator"
  loop:  "{{ results.resources }}"





