---
- name: 'Assert that the cluster has been specified.'
  assert:
    that:
      - clusters  is defined


#- debug:
#    msg: 
#      - "scaleHostpath - {{ scaleHostpath }}"
#      - "secretCounter - {{ secretCounter }}"
#      - "attacher - {{ attacher }}"
#      - "provisioner - {{ provisioner }}"
#      - "driverRegistrar -{{ driverRegistrar}}"
#      - "spectrumScale - {{ spectrumScale }}"


- name: "Get cluster information"
  set_fact:
    api_groups: "{{ lookup('k8s', cluster_info='api_groups') }}"

- name: "Ensure the clusters are valid"
  include_tasks: cluster_check.yml
  loop: "{{ clusters }}"

- name: "Set processed spectrum-scale-config to {{ state }}"
  k8s:
    state: "{{ state }}"
    definition: "{{ lookup('template', 'spectrum_scale.yaml.j2'  ) | from_yaml }}"

- name: "Ensure csi-scale objects are {{ state }}"
  k8s:
    state: "{{ state }}"
    definition: "{{ lookup('template', item.name) | from_yaml }}"
  loop:
    - name: csi-plugin-attacher.yaml.j2
    - name: csi-plugin-provisioner.yaml.j2
    - name: csi-plugin.yaml.j2

