---
# tasks file for ansible-role-csi-scale
- name: "Get cluster information"
  set_fact:
    api_groups: "{{ lookup('k8s', cluster_info='api_groups') }}"

- name: Ensure the plugin configuration is correct
  include_tasks: plugin_config.yml

- name: Ensure csi-scale objects are {{ state }}
  k8s:
    state: "{{ state }}"
    definition: "{{ lookup('template', item.name) | from_yaml }}"
  loop:
    - name: csi-plugin-attacher.yaml.j2
    - name: csi-plugin-provisioner.yaml.j2	 
    - name: csi-plugin.yaml.j2


