---
# tasks file for ansible-role-csi-scale
- name: "Get cluster information"
  set_fact:
    api_groups: "{{ lookup('k8s', cluster_info='api_groups') }}"
    secret_counter: "{{_scale_ibm_com_csiscaleoperator.spec.secretCounter | default(-1) }}"

- name: Ensure the plugin configuration is correct
  include_tasks: plugin_config.yml

- name: Ensure csi-scale objects are {{ state }}
  k8s:
    state: "{{ state }}"
    definition: "{{ lookup('template', item.name) | from_yaml }}"
  loop:
    - name: csi-plugin-attacher.yaml.j2
    - name: csi-plugin-provisioner.yaml.j2
    - name: csi-plugin.yaml.j2


- name: "Set finalizer to {{state}}"
  when: state is match("absent")
  block:
  - name: "Strip the finalizer out of the Custom Resource"
    set_fact: 
      final_stripped: "{{ _scale_ibm_com_csiscaleoperator | combine('metadata': {'finalizers':[]})}}"

  - name: "Write the change to the finalizer"
    k8s:
      state: present
      definition : "{{final_stripped}}"


  
