---
#- debug:
#    msg: 
#      - "scaleHostpath - {{ scaleHostpath }}"
#      - "secretCounter - {{ secretCounter }}"
#      - "attacher - {{ attacher }}"
#      - "provisioner - {{ provisioner }}"
#      - "driverRegistrar - {{ driverRegistrar}}"
#      - "spectrumScale - {{ spectrumScale }}"
#      - "clusters - {{ clusters }}"
#      - "clustersCamelCase - {{clustersCamelCase}}"


- name: "Get cluster information"
  set_fact:
    api_groups: "{{ lookup('k8s', cluster_info='api_groups') }}"

- name: "Ensure the clusters are valid"
  include_tasks: cluster_check.yml
  loop: "{{ clustersCamelCase }}"

- name: "Ensure csi-scale objects are {{ state }}"
  k8s:
    state: "{{ state }}"
    definition: "{{ lookup('template', item.name) | from_yaml }}"
  loop:
    - name: spectrum_scale.yaml.j2 
    - name: csi-plugin-attacher.yaml.j2
    - name: csi-plugin-provisioner.yaml.j2
    - name: csi-plugin.yaml.j2

