---
- name: "Ensure scale_config"
  set_fact: 
    scale_config: '{{ _scale_ibm_com_csiscaleoperator.spec }}'

- name: "Ensure scaleHostpath configured"
  set_fact: 
    csi_scale_hostpath: "{{ scale_config.scaleHostpath }}" 
  
- name: "Ensure clusters configured"
  set_fact: 
    clusters: "{{ scale_config.clusters }}"

- name: "Ensure the clusters are valid"
  include_tasks: cluster_check.yml
  loop:  "{{ clusters }}"

#- name: "Ensure the storage classes are created"
#  include_tasks: storageclass_config.yml
#  loop:  "{{ clusters }}"

  
- name: "Set processed spectrum-scale-config to {{ state }}"
  k8s:
    state: "{{ state }}"
    definition: "{{ lookup('template', 'spectrum_scale.yaml.j2'  ) | from_yaml }}"
