---
# TODO need to make storage class configurable
# TODO pvc configuration

- name: "Refresh Storage Class"
  block: 
    # TODO Not sure if this is "correct", but this is the only way to make it work.
    - name: "Destroy old storage class."
      k8s:
        state: absent
        definition: "{{ lookup('template', 'storageclass.yaml.j2'  ) | from_yaml }}"

    - name: "Ensure cluster[{{ item.id }}] storage class is configured"
      k8s:
        state: "{{ state }}"
        definition: "{{ lookup('template', 'storageclass.yaml.j2'  ) | from_yaml }}"
  when: item.primary is defined and item.primary.primaryFS is defined


