---
# tasks file for ansible-role-csi-scale


- name: "Get cluster information"
  set_fact:
    api_groups: "{{ lookup('k8s', cluster_info='api_groups') }}"

# ====================================================================
# TEST configuration - (XXX Do we want to cut this out? John)
# ====================================================================
- name: "Get spectrum-scale-config from configmaps"
  set_fact: 
    test_scale_config: "{{ lookup('k8s', field_selector='data', 
        resource_name='spectrum-scale-config', kind='configmaps', 
        namespace=lookup( 'vars','namespace' ) ) }}"

- name: "Verify JSON formatting of spectrum-scale-config"
  set_fact:
    scale_cluster: "{{ test_scale_config.data.config | from_json }}"

- name: "Aggregate Secret Names"
  set_fact:
      scale_secrets: "{{ scale_secrets | default([]) | union([item.secrets]) }}"
  loop:  "{{ scale_cluster.clusters }}"

- name: "Verify secrets of spectrum-scale-config"
  k8s_facts:
    kind: secrets
    namespace: "{{ lookup( 'vars','namespace' ) }}"
    name : "{{ item }}"
  loop:  "{{ scale_secrets }}"
  register: result
  failed_when: ( result.resources | length ) == 0

  # Should we attempt to connect?
  #- name: "Check for Spectrum Scale REST server"
  

# ====================================================================
      

- name: 'Set csi-scale objects state={{ state }}'
  k8s:
    state: '{{ state }}'
    definition: "{{ lookup('template', item.name) | from_yaml }}"
  loop:
    - name: csi-plugin-attacher.yaml.j2
    - name: csi-plugin-provisioner.yaml.j2	 
    - name: csi-plugin.yaml.j2
    - name: pvc.yaml.j2
    - name: storageclass.yaml.j2


