---
- debug:
    msg: "{{_scale_ibm_com_csiscaleoperator}}"

- name: Retrieve spectrum-scale-config 
  set_fact: 
    scale_config: _scale_ibm_com_csiscaleoperator
    #scale_config: "{{ 
    #    lookup('k8s', field_selector='data', 
    #     resource_name='csi-scale-operator', 
    #     kind='csi-scale-operators.scale.ibm.com', 
    #     namespace=lookup( 'vars','namespace' ) ) }}"
- name: Ensure hostpath
  set_fact: 
    csi_scale_hostpath: test_scale_config.csi_scale_hostpath 
  

- name: Ensure plugin config
  set_fact: 
    plugin: csi_scale_plugin 


- name: Ensure the clusters are valid
  include_tasks: cluster_check.yml
  loop:  csi_scale_plugin.clusters 
  
- name: Cache clusters as json in config_map
  set_fact:
    spectrum_json_conf: csi_scale_plugin.clusters

- name: "Set processed spectrum-scale-config to {{ state }}"
  k8s:
    state: "{{ state }}"
    definition: "{{ lookup('template', 'spectrum_scale.yaml.j2'  ) | from_yaml }}"
