apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/instance: ssco-ibm-spectrum-scale-csi-operator
    app.kubernetes.io/managed-by: operator
    app.kubernetes.io/name: spectrum-scale-csi-operator
  name: ibm-spectrum-scale-csi-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: ibm-spectrum-scale-csi-operator
  template:
    metadata:
      labels:
        name: ibm-spectrum-scale-csi-operator
    spec:
      containers:
      - command:
        - /usr/local/bin/ao-logs
        - /tmp/ansible-operator/runner
        - stdout
        image: jdunham-rh72-k8s-scale-master.fyre.ibm.com:5000/csi-scale-operator:latest
        imagePullPolicy: Always
        livenessProbe:
          initialDelaySeconds: 15
          periodSeconds: 20
          tcpSocket:
            port: 8080
        name: ansible
        ports:
        - containerPort: 8080
        readinessProbe:
          initialDelaySeconds: 5
          periodSeconds: 10
          tcpSocket:
            port: 8080
        volumeMounts:
        - mountPath: /tmp/ansible-operator/runner
          name: runner
          readOnly: true
      - env:
        - name: WATCH_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: OPERATOR_NAME
          value: ibm-spectrum-scale-csi-operator
        image: jdunham-rh72-k8s-scale-master.fyre.ibm.com:5000/csi-scale-operator:latest
        imagePullPolicy: Always
        livenessProbe:
          initialDelaySeconds: 15
          periodSeconds: 20
          tcpSocket:
            port: 8080
        name: operator
        ports:
        - containerPort: 8080
        readinessProbe:
          initialDelaySeconds: 5
          periodSeconds: 10
          tcpSocket:
            port: 8080
        volumeMounts:
        - mountPath: /tmp/ansible-operator/runner
          name: runner
      serviceAccountName: ibm-spectrum-scale-csi-operator
      volumes:
      - emptyDir: {}
        name: runner
