apiVersion: apps/v1
kind: Deployment
metadata:
  name: ibm-spectrum-scale-csi-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: ibm-spectrum-scale-csi-operator
  template:
    metadata:
      labels:
        name: ibm-spectrum-scale-csi-operator
    spec:
      serviceAccountName: ibm-spectrum-scale-csi-operator
      containers:
        - name: ansible
          image: "quay.io/mew2057/ibm-spectrum-scale-csi-operator:v0.0.1"
          command:
            - /usr/local/bin/ao-logs
            - /tmp/ansible-operator/runner
            - stdout
          imagePullPolicy: Always
          volumeMounts:
            - mountPath: /tmp/ansible-operator/runner
              name: runner
              readOnly: true

        - name: operator
          image: "quay.io/mew2057/ibm-spectrum-scale-csi-operator:v0.0.1"
          imagePullPolicy: Always
          volumeMounts:
            - mountPath: /tmp/ansible-operator/runner
              name: runner
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "ibm-spectrum-scale-csi-operator"
      volumes:
        - name: runner
          emptyDir: {}
