apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/instance: spectrum-scale-csi-operator-deployment-ibm-spectrum-scale-csi-operator
    app.kubernetes.io/managed-by: operator
    app.kubernetes.io/name: spectrum-scale-csi-operator
  name: ibm-spectrum-scale-csi-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: ibm-spectrum-scale-csi-operator
  template:
    metadata:
      labels:
        name: ibm-spectrum-scale-csi-operator
    spec:
      containers:
      - command:
        - /usr/local/bin/ao-logs
        - /tmp/ansible-operator/runner
        - stdout
        image: quay.io/mew2057/ibm-spectrum-scale-csi-operator:v0.0.1
        imagePullPolicy: IfNotPresent
        name: ansible
        volumeMounts:
        - mountPath: /tmp/ansible-operator/runner
          name: runner
          readOnly: true
      - env:
        - name: WATCH_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: OPERATOR_NAME
          value: ibm-spectrum-scale-csi-operator
        image: quay.io/mew2057/ibm-spectrum-scale-csi-operator:v0.0.1
        imagePullPolicy: IfNotPresent
        name: operator
        volumeMounts:
        - mountPath: /tmp/ansible-operator/runner
          name: runner
      serviceAccountName: ibm-spectrum-scale-csi-operator
      volumes:
      - emptyDir: {}
        name: runner
