apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: ibm-spectrum-scale-csi-operator
rules:
  - apiGroups: [ "" ]
    resources: [ "pods", "persistentvolumeclaims", "services", "endpoints", "events", "configmaps",
      "secrets", "secrets/status", "services/finalizers"  ]
    verbs: [ '*' ]
  - apiGroups: [ "apps" ]
    resources: [ "deployments", "daemonsets", "replicasets", "statefulsets" ]
    verbs: [ '*' ]
  - apiGroups: [ "monitoring.coreos.com" ]
    resources: [ "servicemonitors" ]
    verbs: [ "get", "create" ]
  - apiGroups: [ "apps" ]
    resourceNames: [ "ibm-spectrum-scale-csi-operator" ]
    resources: [ "deployments/finalizers" ]
    verbs: [ "update" ]
  - apiGroups: [""]
    resources: [ "pods" ]
    verbs: [ "get" ]
  - apiGroups: [ "apps" ]
    resources: [ "replicasets" ]
    verbs: [ "get" ]
  - apiGroups: [ "scale.ibm.com" ]
    resources: [ '*' ]
    verbs: [ '*' ]

---
# Cluster Role level settings for the ibm-spectrum-scale-csi-operator.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ibm-spectrum-scale-csi-operator
rules:
  - apiGroups: [ "" ]
    resources: [ "persistentvolumeclaims", "persistentvolumes", "configmaps", "secrets"]
    verbs: [ '*' ]
  - apiGroups: ["storage.k8s.io"]
    resources: ["volumeattachments", "storageclasses" ]
    verbs: [ '*' ]
    #verbs: ["get", "list", "watch", "update"]


---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: csi-nodeplugin
rules:
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["get", "list", "update"]
  - apiGroups: [""]
    resources: ["namespaces"]
    verbs: ["get", "list"]
  - apiGroups: [""]
    resources: ["persistentvolumes"]
    verbs: ["get", "list", "watch", "update"]
  - apiGroups: ["storage.k8s.io"]
    resources: ["volumeattachments"]
    verbs: ["get", "list", "watch", "update"]

---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: external-attacher-runner
rules:
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["get", "list", "watch", "update"]
  - apiGroups: [""]
    resources: ["persistentvolumes"]
    verbs: ["get", "list", "watch", "update"]
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["storage.k8s.io"]
    resources: ["volumeattachments"]
    verbs: ["get", "list", "watch", "update"]

---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: external-provisioner-runner
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list"]
  - apiGroups: [""]
    resources: ["persistentvolumes"]
    verbs: ["get", "list", "watch", "create", "delete"]
  - apiGroups: [""]
    resources: ["persistentvolumeclaims"]
    verbs: ["get", "list", "watch", "update"]
  - apiGroups: ["storage.k8s.io"]
    resources: ["storageclasses"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["list", "watch", "create", "update", "patch"]
