apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: csi-scale-operators.scale.ibm.com
spec:
  group: scale.ibm.com
  names:
    kind: CSIScaleOperator
    listKind: CSIScaleOperatorList
    plural: csi-scale-operators
    singular: csi-scale-operator
  scope: Namespaced
  subresources:
    status: {}
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
  validation:
    openAPIV3Schema:
      type: object
      properties:
        spec:
          type: object
          properties:
            csi_scale_hostpath:
              description: "The path to the gpfs file system mounted on the host machine."
              type: string

            csi_clusters:
              description: "A collection of gpfs cluster properties for the csi driver to mount."
              type: array
              required:
                - id
              properties:
                id:
                  description: "The cluster id of the gpfs cluster specified (mandatory)."
                  type: string

                primary:
                  description: "The primary file system for the GPFS cluster."
                  type: object
                  properties:
                    primaryFS:
                      description: "The name of the primary filesystem."
                      type: string

                    primaryFset:
                      description: "The name of the primary fileset, created in primaryFS."
                      type: string

                secureSslMode:
                    description: "Require a secure SSL connection to connect to GPFS."
                    type: boolean

                secrets:
                  description: "A string specifying a secret resource name.."
                  type: string

                cacert: 
                  description: "A string specifying a cacert resource name."
                  type: string

                restApi:
                  description: "A collection of targets for REST calls." 
                  type: array
                  properties:
                    guiHost:
                      description: "The hostname of the REST server."
                      type: string

                    guiPort:
                      description: "The port number running the REST server."
                      type: string
            
