apiVersion: apps/v1
kind: Deployment
metadata:
  name: csi-scale-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: csi-scale-operator
  template:
    metadata:
      labels:
        name: csi-scale-operator
    spec:
      serviceAccountName: csi-scale-operator
      containers:
        - name: ansible
          command:
          - /usr/local/bin/ao-logs
          - /tmp/ansible-operator/runner
          - stdout
          image: "csi-scale-operator:latest"
          imagePullPolicy: "IfNotPresent"
          volumeMounts:
          - mountPath: /tmp/ansible-operator/runner
            name: runner
            readOnly: true
        - name: operator
          image: "csi-scale-operator:latest"
          imagePullPolicy: "IfNotPresent"
          volumeMounts:
          - mountPath: /tmp/ansible-operator/runner
            name: runner
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "csi-scale-operator"
              #            - name: ANSIBLE_VERBOSITY
              #value: "4"
      volumes:
        - name: runner
          emptyDir: {}
