kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: csi-scale-operator
subjects:
- kind: ServiceAccount
  name: csi-scale-operator
roleRef:
  kind: Role
  name: csi-scale-operator
  apiGroup: rbac.authorization.k8s.io

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: csi-scale-operator
subjects:
  - kind: ServiceAccount
    name: csi-scale-operator
    namespace: default
roleRef:
  kind: ClusterRole
  name: csi-scale-operator
  apiGroup: rbac.authorization.k8s.io

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
    name: csi-nodeplugin
subjects:
     - kind: ServiceAccount
       name: csi-nodeplugin
       namespace: default
roleRef:
    kind: ClusterRole
    name: csi-nodeplugin
    apiGroup: rbac.authorization.k8s.io

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
    name: csi-provisioner-role
subjects:
     - kind: ServiceAccount
       name: csi-provisioner
       namespace: default
roleRef:
    kind: ClusterRole
    name: external-provisioner-runner
    apiGroup: rbac.authorization.k8s.io

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
    name: csi-attacher-role
subjects:
     - kind: ServiceAccount
       name: csi-attacher
       namespace: default
roleRef:
    kind: ClusterRole
    name: external-attacher-runner
    apiGroup: rbac.authorization.k8s.io

