apiVersion: v1
kind: ServiceAccount
metadata:
  name: csi-scale-operator

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: csi-attacher

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: csi-nodeplugin

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: csi-provisioner

