apiVersion: v1
kind: ConfigMap
metadata: 
    # IMPORTANT THE OPERATOR LOOKS FOR THIS!
    name: 'spectrum-scale-config'
data: 
  # 
  scale_hostpath: "/ibm/fs1"

  plugin: | 
    clusters: 
      - id: "2120508922778391120"
        secrets: "secret1"
        secureSslMode: false
        primary:
          primaryFS: "fs1"
          primaryFset: "csiFset2"
        restAPI: 
          - guiHost: "doomfang-vm5.tuc.stglabs.ibm.com"

