---
- name: Set environment facts
  set_fact:
    OPERATOR_SDK_VER: "v0.10.0"
    OPERATOR_VERSION: "0.0.1"

- name: Ensure 'python3' is installed
  package:
    name: "{{packages}}"
  vars:
    packages:
    - python36
    - python36-pip
  #- jq

- name: Ensure 'python3' requirements are installed
  pip: 
    requirements: "{{playbook_dir}}/common/requirements-dev.txt"
    executable: pip3

- name: Ensure 'operator-sdk' is installed
  get_url:  
    url: "https://github.com/operator-framework/operator-sdk/releases/download/{{release}}/operator-sdk-{{release}}-x86_64-linux-gnu"
    dest: /usr/local/bin/operator-sdk
    mode: '0755'
  vars:
    release: "{{OPERATOR_SDK_VER}}"

