apiVersion: scale.ibm.com/v1alpha1
kind: CSIScaleOperator
metadata:
  labels:
    app.kubernetes.io/instance: ssco-csi-scale-operator
    app.kubernetes.io/managed-by: operator
    app.kubernetes.io/name: spectrum-scale-csi-operator
  name: csi-scale-operator
spec:
  clusters:
  - id: '11832033572270148010'
    primary:
      primaryFS: fs1
      primaryFset: csiFset2
    restApi:
    - guiHost: jdunham-rh72-k8s-scale-master.fyre.ibm.com
    secrets: secret1
    secureSslMode: false
  scaleHostpath: /ibm/fs1
status: {}
