/ibm/fs1/doomfang/go/src/github.ibm.com/jdunham/ibm-spectrum-scale-csi-operator/stable/ibm-spectrum-scale-csi-operator-bundle/operators/ibm-spectrum-scale-csi-operator/deploy/olm-catalog/ibm-spectrum-scale-csi-operator/0.0.1//ibm-csi-scale-ClusterRoleBinding_csi-provisioner-role.yaml
...
