apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[{"apiVersion":"scale.ibm.com/v1alpha1","kind":"CSIScaleOperator","metadata":{"name":"csi-scale-operator"},"spec":{"clusters":[{"id":"2120508922778391120","primary":{"primaryFS":"fs1","primaryFset":"csiFset2"},"restApi":[{"guiHost":"doomfang-vm5.tuc.stglabs.ibm.com"}],"secrets":"secret1","secureSslMode":false}],"scaleHostpath":"/ibm/fs1"},"status":{}}]'
    capabilities: Basic Install
    categories: Storage
    containerImage: quay.io/mew2057/ibm-spectrum-scale-csi-operator:v0.0.1
    createdAt: Wed Oct  9 06:41:31 MST 2019
    description: An operator for the CSI scale plugin offering.
    repository: https://github.com/IBM/ibm-spectrum-scale-csi-operator/stable/ibm-spectrum-scale-csi-operator-bundle/operators/ibm-spectrum-scale-csi-operator
  name: ibm-spectrum-scale-csi-operator.v0.0.1
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: Represents a deployment of the IBM CSI Spectrum Scale plugin.
      displayName: IBM CSI Spectrum Scale App
      kind: CSIScaleOperator
      name: csiscaleoperators.scale.ibm.com
      resources:
      - kind: csiscaleoperators
        name: ''
        version: v1alpha1
      - kind: Deployment
        name: ''
        version: v1
      - kind: Secret
        name: ''
        version: v1
      - kind: Pod
        name: ''
        version: v1
      - kind: StatefulSet
        name: ''
        version: v1beta1
      - kind: DaemonSet
        name: ''
        version: v1beta2
      - kind: ConfigMap
        name: ''
        version: v1
      specDescriptors:
      - description: Sidecar container image for the csi spectrum scale plugin pods.
        displayName: driverRegistrar
        path: driverRegistrar
        x-descriptors: []
      - description: The path to the gpfs file system mounted on the host machine.
        displayName: scaleHostpath
        path: scaleHostpath
        x-descriptors: []
      - description: Provisioner image for csi (actually issues provision requests).
        displayName: provisioner
        path: provisioner
        x-descriptors: []
      - description: Image name for the csi spectrum scale plugin container.
        displayName: spectrumScale
        path: spectrumScale
        x-descriptors: []
      - description: A collection of gpfs cluster properties for the csi driver to
          mount.
        displayName: clusters
        path: clusters
        x-descriptors: []
      - description: Attacher image for csi (actually attaches to the storage).
        displayName: attacher
        path: attacher
        x-descriptors: []
      - description: An internal counter used by the operator to trigger reloads on
          secret change.
        displayName: secretCounter
        path: secretCounter
        x-descriptors: []
      - description: A string specifying a cacert resource name.
        displayName: cacert
        path: clusters.cacert
        x-descriptors: []
      - description: Require a secure SSL connection to connect to GPFS.
        displayName: secureSslMode
        path: clusters.secureSslMode
        x-descriptors: []
      - description: A string specifying a secret resource name.
        displayName: secrets
        path: clusters.secrets
        x-descriptors: []
      - description: A collection of targets for REST calls.
        displayName: restApi
        path: clusters.restApi
        x-descriptors: []
      - description: The primary file system for the GPFS cluster.
        displayName: primary
        path: clusters.primary
        x-descriptors: []
      - description: The cluster id of the gpfs cluster specified (mandatory).
        displayName: id
        path: clusters.id
        x-descriptors: []
      - description: The hostname of the REST server.
        displayName: guiHost
        path: clusters.restApi.guiHost
        x-descriptors: []
      - description: The port number running the REST server.
        displayName: guiPort
        path: clusters.restApi.guiPort
        x-descriptors: []
      - description: The name of the primary filesystem.
        displayName: primaryFS
        path: clusters.primary.primaryFS
        x-descriptors: []
      - description: The name of the primary fileset, created in primaryFS.
        displayName: primaryFset
        path: clusters.primary.primaryFset
        x-descriptors: []
      statusDescriptors:
      - description: The active status of the operator
        displayName: conditions
        path: conditions
        x-descriptors: []
      - description: Indicates that the plugin is running.
        displayName: isRunning
        path: conditions.isRunning
        x-descriptors: []
      version: v1alpha1
  description: An Operator used to deploy and manage your Spectrum CSI Plugin.
  displayName: IBM Spectrum Scale CSI Plugin Operator
  install:
    spec:
      clusterPermissions:
      - rules:
        - apiGroups:
          - ''
          resources:
          - persistentvolumeclaims
          - persistentvolumes
          - configmaps
          - secrets
          verbs:
          - '*'
        - apiGroups:
          - storage.k8s.io
          resources:
          - volumeattachments
          - storageclasses
          verbs:
          - '*'
        serviceAccountName: ibm-spectrum-scale-csi-operator
      - rules:
        - apiGroups:
          - ''
          resources:
          - nodes
          verbs:
          - get
          - list
          - update
        - apiGroups:
          - ''
          resources:
          - namespaces
          verbs:
          - get
          - list
        - apiGroups:
          - ''
          resources:
          - persistentvolumes
          verbs:
          - get
          - list
          - watch
          - update
        - apiGroups:
          - storage.k8s.io
          resources:
          - volumeattachments
          verbs:
          - get
          - list
          - watch
          - update
        serviceAccountName: csi-nodeplugin
      - rules:
        - apiGroups:
          - ''
          resources:
          - events
          verbs:
          - get
          - list
          - watch
          - update
        - apiGroups:
          - ''
          resources:
          - persistentvolumes
          verbs:
          - get
          - list
          - watch
          - update
        - apiGroups:
          - ''
          resources:
          - nodes
          verbs:
          - get
          - list
          - watch
        - apiGroups:
          - storage.k8s.io
          resources:
          - volumeattachments
          verbs:
          - get
          - list
          - watch
          - update
        serviceAccountName: external-attacher-runner
      - rules:
        - apiGroups:
          - ''
          resources:
          - secrets
          verbs:
          - get
          - list
        - apiGroups:
          - ''
          resources:
          - persistentvolumes
          verbs:
          - get
          - list
          - watch
          - create
          - delete
        - apiGroups:
          - ''
          resources:
          - persistentvolumeclaims
          verbs:
          - get
          - list
          - watch
          - update
        - apiGroups:
          - storage.k8s.io
          resources:
          - storageclasses
          verbs:
          - get
          - list
          - watch
        - apiGroups:
          - ''
          resources:
          - events
          verbs:
          - list
          - watch
          - create
          - update
          - patch
        serviceAccountName: external-provisioner-runner
      deployments:
      - name: ibm-spectrum-scale-csi-operator
        spec:
          replicas: 1
          selector:
            matchLabels:
              name: ibm-spectrum-scale-csi-operator
          strategy: {}
          template:
            metadata:
              labels:
                name: ibm-spectrum-scale-csi-operator
            spec:
              containers:
              - command:
                - /usr/local/bin/ao-logs
                - /tmp/ansible-operator/runner
                - stdout
                image: quay.io/mew2057/ibm-spectrum-scale-csi-operator:v0.0.1
                imagePullPolicy: Always
                name: ansible
                resources: {}
                volumeMounts:
                - mountPath: /tmp/ansible-operator/runner
                  name: runner
                  readOnly: true
              - env:
                - name: WATCH_NAMESPACE
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.annotations['olm.targetNamespaces']
                - name: POD_NAME
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.name
                - name: OPERATOR_NAME
                  value: ibm-spectrum-scale-csi-operator
                image: quay.io/mew2057/ibm-spectrum-scale-csi-operator:v0.0.1
                imagePullPolicy: Always
                name: operator
                resources: {}
                volumeMounts:
                - mountPath: /tmp/ansible-operator/runner
                  name: runner
              serviceAccountName: ibm-spectrum-scale-csi-operator
              volumes:
              - emptyDir: {}
                name: runner
      permissions:
      - rules:
        - apiGroups:
          - ''
          resources:
          - pods
          - persistentvolumeclaims
          - services
          - endpoints
          - events
          - configmaps
          - secrets
          - secrets/status
          verbs:
          - '*'
        - apiGroups:
          - apps
          resources:
          - deployments
          - daemonsets
          - replicasets
          - statefulsets
          verbs:
          - '*'
        - apiGroups:
          - monitoring.coreos.com
          resources:
          - servicemonitors
          verbs:
          - get
          - create
        - apiGroups:
          - apps
          resourceNames:
          - ibm-spectrum-scale-csi-operator
          resources:
          - deployments/finalizers
          verbs:
          - update
        - apiGroups:
          - ''
          resources:
          - pods
          verbs:
          - get
        - apiGroups:
          - apps
          resources:
          - replicasets
          verbs:
          - get
        - apiGroups:
          - scale.ibm.com
          resources:
          - '*'
          verbs:
          - '*'
        serviceAccountName: ibm-spectrum-scale-csi-operator
    strategy: deployment
  installModes:
  - supported: true
    type: OwnNamespace
  - supported: true
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - IBM
  - GPFS
  - Spectrum Scale
  labels:
    operator: ibm-spectrum-scale-csi-operator
  links:
  - name: CSI Developer Documentation
    url: https://kubernetes-csi.github.io/docs/
  maintainers:
  - email: jdunham@us.ibm.com
    name: John Dunham
  - email: yadayada@in.ibm.com
    name: Yadavendra Yadav
  maturity: alpha
  provider:
    name: IBM
  version: 0.0.1
  icon: 
  - base64data: iVBORw0KGgoAAAANSUhEUgAAAGQAAABnCAMAAADBqBfIAAAAsVBMVEUAAACIyVeGxlaGx1aGxlaMylyM0FmJyliPymKOymGGxlaHx1aHx1iHx1eKylqKy1qGx1aHyFeKylmMyV6Gx1aGxlaHyFeMzFyGx1aHx1aIyViKylmLyluGx1aIyFiJylmHx1aIyViJylmLyluIyFeIyVeJylmMy16HyFeIyFeIyViJyliHyFeIyVeHyFeIyFeIyViIyViKylqHyFeIyVeJylmIyViIyFeLy1qFxVWHx1f7ghN0AAAAOXRSTlMAC2qj/JM5qx0juuRL2A8E6s0oQvX4phPy7oJGGd6PMdFhIQmYiVwGtJ5V275usH14Zi3Dc1E9xzb8nESrAAAEv0lEQVRo3u2a6VbiQBCFC4zImrCEsCSGJawOO4iW7/9gM8hAlV1JJNCc45kz3z8HmZvu2rpvhJ+J+WLBvVk1sVKFu9Ir4AEnB3cj94Z/qbfhPpgPBhKFF9CPlW7iV976oJlRCQWGkwWNVCdIsBW1lqCLho9EtwPLOv34rCk06RaesT8r0XNYCsw0VE2myySW5ulf8yw0gxTcyCuecfo8E55pLXAzFTxSqcEXUstTBrzDzXSOO9UDQXaBBwaggSlifdiAMPZviGUPriW7pgz+eMrFdMw5rTmdrE21P4wOlWJsEZlwoosl9/I29do8BBoSssY/THIXRvpvm4qo5fYsPJvGhWPV+BdUjeecm3kAEvdQHgMTJP65oX3XaSyfNYylXOT2NLPGIoysb5ZqseVdZh12LjZkWqfGWBRbkEfiyYsMRpfPCnVLgl0ZOfk9KBTZzPlop76drvJA4sqpNWiI6WnTp+UiCIZsTwuih2wWGEJ5l1KrZsrns7LW9wJv6KAQDPki2+wHWX39GRIOcNIUjIloU/MCS4feGPoOsl8XG/vCfj1cpNIR4WTpUB8e96f2hoQvQrOy40RkHVX5Uy9y9IVntrp1oIbGMSJFPnKgDia2/92ajBN9pDCIFskqfZxVRnkeyEUSE+Wk93ihyHuJBeNxDJJMBYlhKrmI98SrewMCkXjNdUKR1EoUQzjjgc1Cs08iErTYAy4tiGPDqs9oJxBJ0fceU2LgitBQOj9cIzLriHou4SAr73jXi8ihUf0cGvbKkqPmWhF1mHu+fQrxCBSerhXJKMf7AhKL6j1Eal3lnuV7ukVyExTYc0uniNluYhiVokaRCUbh6hPJYxTFnyaSrR1wQZtItfYJhKBJhPgv8l/kXxIZ/TpQ0Vfx61+fhB5TdbeVHyeyr6CALu23ilDQyihZZAG0iJARaSgSpVcATSKEt0BGaw2gUYRwuyeJ+kMAmkQc1Vewei08sO0LL+P5WhFsrUzVUhiE2fTvE8QrRE48vwpPryeakI94kwgasw3EQ55LMhHYz5AYeHHGUondl9rmZSLkYMqbr2TjoDCnE4hAqm2zwitCCCbd5cmcvkiEyD1wm6wKDLnY9RguFFHTP0MeinAe98z4sIdqqvuRIpjPCh+WP22aJfJD6IWI+mm0CNq+pXpdflPe6M02El03wg+VIicKa/muyfjqoVi877dWolqZzwicFyS2G/Fk3GXxMyXhqMjr9pGy8rh89k1zwkNpYRh5GQxKhzD32C3wj9XQWI91ISE9l832u0aR2vH/QBqqymmiKR7Em9qsNjMQjjdAYtYJ8VCIRzOuURZGQMSF2NgJJ39ejzSnG/ybQxGMKMPV6IR1K+65cKwu5U0fBFHm5hTCyG3tdnhDFo0yltwUMeaFWArCmR5r2YILcSuIO0hIw0B72IAEpPOUPdteEL3qxYZqnRplYkbkYKoESwNnoIFGgU5aoc3mVYPIkF7thFvPrTHcSt8+j78RMLJ0hNjBrYyMsH4UfDGn4Wb6E97QPHFbaaZBBy6fEb4FnYp4e6b7zyTKCyQo6TQQOCwG/DSuF2mnGr0x6ITmMzFtwF2Y05x/q8K9MJ2/we+BXuRrh/puDPfFcqdZ+In8Bg8Knr3O+ZToAAAAAElFTkSuQmCC
    mediatype: image/png

